// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.meng.nettynio.nettyproto.bean;

public interface MyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meng.nettyproto.bean.MyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_name = 1;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string real_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
