// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.meng.nettynio.nettyproto.bean;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meng.nettyproto.bean.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
