// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.meng.nettynio.nettyproto.bean;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meng.nettyproto.bean.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_name = 1;</code>
   */
  java.lang.String getRequestName();
  /**
   * <code>string request_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestNameBytes();
}
