// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.meng.nettynio.nettyproto.bean;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meng.nettyproto.bean.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_name = 1;</code>
   */
  java.lang.String getResponseName();
  /**
   * <code>string response_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseNameBytes();
}
