// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.meng.nettynio.nettyproto.bean;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meng.nettyproto.bean.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.meng.nettyproto.bean.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.meng.nettynio.nettyproto.bean.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.meng.nettyproto.bean.StudentResponse studentResponse = 1;</code>
   */
  com.meng.nettynio.nettyproto.bean.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.meng.nettyproto.bean.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.meng.nettyproto.bean.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.meng.nettynio.nettyproto.bean.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.meng.nettyproto.bean.StudentResponse studentResponse = 1;</code>
   */
  com.meng.nettynio.nettyproto.bean.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
